# Generated by Django 3.1.5 on 2021-01-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_eventsjoined_peruutus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsjoined',
            name='Peruutus',
        ),
        migrations.AddField(
            model_name='eventsjoined',
            name='date_cancel',
            field=models.DateField(null=True),
        ),
    ]
