# Generated by Django 3.1.5 on 2021-02-07 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210207_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='memberscancelled',
        ),
        migrations.DeleteModel(
            name='EventsCancelled',
        ),
    ]
