# Generated by Django 3.1.5 on 2021-02-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210207_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='bio',
            field=models.TextField(blank=True, default=None, max_length=500),
        ),
    ]
